function(install_project)
	set(CMAKE_INSTALL_DIR "${CMAKE_SOURCE_DIR}/${PROJECT_NAME}-${PROJECT_VERSION}-${CMAKE_BUILD_TYPE}-${GIT_COMMIT_HASH}")

	set(PLUGIN_FILES
		"${CMAKE_SOURCE_DIR}/snippets.tmux"
	)

	install(TARGETS "${UI_EXECUTABLE}"
		RUNTIME DESTINATION "${CMAKE_INSTALL_DIR}"
		CONFIGURATIONS Release Debug
	)

	install(FILES ${PLUGIN_FILES}
		DESTINATION "${CMAKE_INSTALL_DIR}"
		PERMISSIONS
			OWNER_READ OWNER_WRITE OWNER_EXECUTE
			GROUP_READ GROUP_EXECUTE
			WORLD_READ WORLD_EXECUTE
		CONFIGURATIONS Release Debug
	)

	install(DIRECTORY "${CMAKE_SOURCE_DIR}/data/"
		DESTINATION "${CMAKE_INSTALL_DIR}/data"
		USE_SOURCE_PERMISSIONS
		CONFIGURATIONS Release Debug
	)

	install(DIRECTORY "${CMAKE_SOURCE_DIR}/scripts/"
		DESTINATION "${CMAKE_INSTALL_DIR}/scripts"
		USE_SOURCE_PERMISSIONS
		CONFIGURATIONS Release Debug
		FILES_MATCHING PATTERN "*.sh"
	)
endfunction()